### ISSUE TITLE
Arguments sorting

### ISSUE THREAD

**Issue by moustachu** [DemocracyOS/democracyos#1157]
Hello guys, 

It seems that the arguments sorting options are not working anymore. Changing the option value to _newer_ or _older first_ keeps the sorting based on the score. 

We detected the problem on a customize version in Europe but I get the same behavior on https://app.democracyos.org

Looking at the code, it seems that `lib/comment-filter` wasn't completly migrated  like `lib/topic-filter`, or it's missing a few things. My guess is something between the `change` event on the dropdown and the `refresh` of the list component. 

I could fix this but I need a few guidelines on the proper way to do it.

**Comment by mjlescano** [comment]
Hi @moustachu,

This specific bug is because the comments are not beign sorted correctly on backend [here](https://github.com/DemocracyOS/democracyos/blob/master/lib/db-api/comment.js#L137).

Nevertheless, the migration is almost done in #1109, with the last changes at the branch [ben-pr-p-refactor/comments](https://github.com/DemocracyOS/democracyos/tree/ben-pr-p-refactor/comments). It would be awesome if you can test it and fix it if anything broken :)

**Comment by moustachu** [comment]
Great ! The new comment api fixes everything.

Quick test report : 
+ everything went fine with merging `ben-pr-p-refactor/comments` with the `master`  
The code can be found [here](https://github.com/democracy-os-fr/app/tree/comments)
+ we still to add a migration case for the topic comments, to field `topicId` for the `comments` collection need to set. I did it manually on the database and everything is working fine.
+ I pull and merge the [code](https://github.com/democracy-os-fr/app/tree/d21-iframe) to a live instance http://app.opencop.org/

Thanks for the help !

I'll give a try the migration code later this week.
