### ISSUE TITLE
Anonymous voting

### ISSUE THREAD

**Issue by VictorW1** [DemocracyOS/democracyos#1180]
As a user, there is a good chance I would like to have my identity hidden when I vote. Currently, there is no setting on a topic to set it to anonymous voting.

For me as a maintainer of Dem.OS, I'd like to make all of my topics anonymous. 

In the Gitter, @gvilarino said:

gvilarino
Jan 07 11:00
@VictorW1 it should be as easy as adding the hide class to the proper label/element
VictorW1
Jan 09 17:46
Interesting. Can you tell me which file I should be looking at?
gvilarino
Jan 12 16:25
Well it depends on what you're looking at. Best course of action is inspect the dom, find the elem and see what style it resolves to. Also the elem ID so you can set a custom style for it

I will be following this issue to see if there is any progress and I will do my best to come up with a solution as well- however I am not an experienced node developer.

**Comment by franciclo** [comment]
I like this, i was talkiing with a colleage who works on wikimedia, he says 80% of wikipedia contribs are anomymous and also is 80% of spam. This tells us that anonymity helps some people to express themselves more freely, and also helps to spam, but i think is a cost we must take.

**Comment by gvilarino** [comment]
I don't agree with this; even if it may be an option, the whole idea behind DemocracyOS is that participation is more open and transparent. It's like public audiences, where you can't hide who you are.
If this exists as an option (not in control of users, but platform managers), then it should be disclosed in the end, at some point. It's the only way you can trust the result as real, because you can see who voted.

**Comment by franciclo** [comment]
Good point @gvilarino, tough i don`t think it would have a negative effect in the openness, it would definetly decrease transparency hence accountabilty and that would be a killer for me, i will talk to the team and close this if we feel is not in our objectives.

**Comment by gvilarino** [comment]
Again, I wouldn't oppose if it were an optional setting, although I'd never offer it as a default, and never recommend it.

Our goal is to promote open, honest debates around policy making. Vote secrecy makes much more sense in election voting.

**Comment by dhowell5** [comment]
I am a very private person. I and the largely silent majority like me LIKE
being "heard" (voting) but often specifically won't engage socially in
order to avoid confrontation. Does that mean we shouldn't have a say? Or
that we should be forced to pretend to extroversion in order to have a say?

Just my 2 cents

**Comment by franciclo** [comment]
We are working to add some topics types, were you could choose what type of topic you want to use, anon voting could be a proposal for one of those.
I also personally don't agree that you are being forced to pretend extroversion by having your user data exposed, i mean it isn't the comments section were you engage in conversations.

**Comment by VictorW1** [comment]
My project has been dormant for a few months, but this was a real pain point last year during demos. There should be an option for anonymous voting as @dhowell5 mentioned. Especially when there's a small user group using the system, where you know the others using it. Or even where the system is implemented in a country with a lot of corruption. Several years ago I was discussing transparent government in Chicago and one individual from South Africa was telling me- sure fine in Canada you can express yourself on the internet without risk in general. But in a country like his, he would only ever post things on the internet praising the ruling party, as anything contrary to that may lead to his persecution. Highlights the reality of different parts of the world, and DemocracyOS should be universal.
Thanks.

**Comment by dhowell5** [comment]
@gvilarino said: 
>  It's the only way you can trust the result as real, because you can see who voted.

A grantedly more difficult alternative solution (trust due to public voting) would be a more robust voting system that is transparent/verifiable yet does not expose identity. (please notice I said "more difficult" :).

There are a number of folks working on blockchain-ish voting systems that provide just such verifiability so perhaps simply planning for a pluggable voting module for DOS in FUTURE?

Whether or not folks should be able to have their vote private will probably always lead to debate. 

Maybe the individual voter should decide for himself and public/private votes tallied separately so that the viewer of the outcome can decide validity for herself????

Lacking other, fairly easy to implement solutions, that last would have to get my vote.

(IFF I had a vote, I mean. I realize I do not. I'm just trying to express my opinion, not upset anyone's "apple cart" ;-)

**Comment by gvilarino** [comment]
I understand your concerns and suggestions, although this is not one of our top priorities ATM.

But PRs are always welcome :D

**Comment by franciclo** [comment]
Closing this since it is not in our priorities. Wil reopen if this topic comes up.
