### ISSUE TITLE
Homepage: search

### ISSUE THREAD

**Issue by peckjon** [DemocracyOS/democracyos#1193]
There's no obvious way to search across forums/topics from the app homepage.

**Comment by votedave** [comment]
Agreed - no search on front page is impossible, sorry but anyone without a URL for the page they're looking for is trapped longer their interest span.  It would also be great to filter anything off the front page without active threads or voting.
While it's anyone's democratic right to engage, test the water, start a page, not all will rise to activity.  This again detracts from the real positive energy needed on the land page and busy sites and content create that, not TEST 123, Just Checking et al.
Thanks so much for the great effort, this rebirth of democracy has been coming since the start of electricity and is as undeniable as that energy.
Cheers Andrew

**Comment by franciclo** [comment]
We definetly need search, among forums, and topic as well, i like how github search add like a tag to the search bar depending on where you are, so you search within that scope. We could search by tags, but first we need to tag everything #1236 #1364 
Filters also will be great.

@votedave check out #1251 were we discuss sorting of forums.

**Comment by mjlescano** [comment]
My recommendation is to use https://github.com/blahah/yunodb, it has the advantage to no need a separate service running (like solr or Lucene).

**Comment by solanoepalacio** [comment]
We are making a search feature implementation that is related to this issue. We have started a new issue called 'Global search'. You can find it:

https://github.com/DemocracyOS/democracyos/issues/1385

Any comments will be appreciated.

**Comment by mjlescano** [comment]
Closing this issue as it is going to be done on #1385
