### ISSUE TITLE
"Not Acceptable" on `/api/forums/mine`

### ISSUE THREAD

**Issue by Schniz** [DemocracyOS/democracyos#1196]
Hey there! :wave: 
My organization is trying to install this app in our internal, isolated network.
[we have created a script that turns the CDNs to local files](https://gist.github.com/Schniz/62becabdab4fc13f9b5b) which you can download too :smile:

when the app calls to `/api/forum/mine?random=0.9733764010015875` for creating a new democracy, we get `406 Not Acceptable` response.
Anyone knows how to fix that?

Thanks :smile:

\cc @rfedida

**Comment by mjlescano** [comment]
Hi @Schniz!

That's awesome :dancer:, really. 

Not sure where you are getting the error, but:

Usually, the 'Not Acceptable' error is because you are not sending an `Accept: application/json` header with the request.

`/api/forum/mine` is the api call to query your existent forum, not for creating it. If you don't have any forum it returns an error, but it's not a real error, it's just for easier response handling.

For creating a new forum, the endpoint is `POST /api/forum`, check it out here: https://github.com/DemocracyOS/democracyos/blob/master/lib/forum-api/index.js#L82

**Comment by Schniz** [comment]
Hey
I've followed the [installation instructions on your docs](http://docs.democracyos.org/install.html):
* Launching mongod
* Clone
* `make`

The app runs yet I can't create democracies :sob: 

Here is a screencast of my trial:

![issue mov](https://cloud.githubusercontent.com/assets/2054772/14136483/b31ec308-f66b-11e5-92ca-91eaa2081162.gif)

**Comment by mjlescano** [comment]
Hi!
Thats a bug, I'm going to fix it here: https://github.com/DemocracyOS/democracyos/issues/1198

You have the config option `multiForum` set to `false`, to let your users create forum you should set it to `true`. Keep in mind that that's an experimental functionality, several changes are expected soon.

For further technical questions, please refer to our [Gitter Channel](https://gitter.im/DemocracyOS/democracyos).

**Comment by Schniz** [comment]
thanks! that's fixed. :smile: 

If you are into it, I published [the Dockerfile](https://gist.github.com/Schniz/dc208348cf30d6c4bdfc04e74e492de8) that uses the script.

have fun :dancer:
