### ISSUE TITLE
DaoHub governance

### ISSUE THREAD

**Issue by bhack** [DemocracyOS/democracyos#1230]
Are we interested in [DaoHub governance topics](https://forum.daohub.org/t/dao-2-0-and-governance-2-0-revamp-proposal/3718)? Seems that this is a real interesting "on the road" experiment.

**Comment by bhack** [comment]
See also the governante thread at https://forum.daohub.org/t/getting-to-know-dao-2-0/2776

**Comment by bhack** [comment]
Curators and democracy https://forum.daohub.org/t/lets-define-the-curator-role/4698

**Comment by bhack** [comment]
Delegates and liquid democracy https://www.reddit.com/r/TheDao/comments/4n59i1/dthpool_fluid_democracy_for_the_dao/

**Comment by gvilarino** [comment]
Thanks for reaching out and sharing those links. It seems a lot of the DAO community is going through the same discussions we've been having internally and as a community since the beginning of DemocracyOS.

Personally, I find the DAO itself to be a very interesting experiment from which there is much to be learned, although it is, as any organisation, vulnerable to exploits, as we've seen recently. I hope Ethereum climbs out of the pit they've fallen into, since a stable, secure, programmable blockchain platform could provide value for many kinds of applications.

Regarding DemocracyOS, blockchain support is not one of our priorities at the moment; we're more focused on addressing citizens' and governments' real needs in terms of digital access, interaction and impact, and since we're a small non-profit, we try to focus on as little topics as possible, while maximising value output for our users.

I do think blockchain-based persistence will be viable for systems like ours at some point in the future, in terms of ease of integration and user adoption, but we'll see how these techs evolve and are used before we make a move on that direction.

**Comment by bhack** [comment]
So are Democracyos and Democracy  two separated project and orgs now?

**Comment by gvilarino** [comment]
I don't really think I follow. Democracy is a government system, I don't know an organisation called Democracy.

Do you mean www.democracy.com ?

**Comment by bhack** [comment]
Sorry was the autocompletion I mean Democracy.earth.

**Comment by gvilarino** [comment]
We are not related, nor have ever been, to that organisation, nope.

**Comment by bhack** [comment]
OK sorry I think that you was repeated with http://democracy.earth with Pia and Santiago.

**Comment by gvilarino** [comment]
Nope, we aren't. Why would you think that?

**Comment by bhack** [comment]
http://www.theatlantic.com/international/archive/2014/07/designing-an-operating-system-for-democracy/374526/

**Comment by gvilarino** [comment]
Pía was indeed a part of this organisation at some point, Santiago wasn't formally, and we haven't been working with them for more than a year, and we never had anything to do with their other org.

**Comment by gvilarino** [comment]
In any case, I guess this isn't a relevant issue for this repo, I'm closing this since there's not a clear goal for it. If you'd like to discuss tech additions for our app please see #1214 or open a specific issue/request that complies with [our contribution guidelines](https://github.com/DemocracyOS/democracyos/blob/master/CONTRIBUTING.md#reporting-bugs--requesting-features).

Thanks!

**Comment by santisiri** [comment]
@bhack I started the development of DemocracyOS. @gvilarino joined 1 year later and mantained it since.
