### ISSUE TITLE
Fix tagging implementation

### ISSUE THREAD

**Issue by lee-b** [DemocracyOS/democracyos#1236]
When I create a new Democracy on app.democracyos.org, and then create a new issue, the list of available tags seems to be pre-populated, and unchangeable, in a drop-down list.  Worse, the tags seem to be in another language than that of the user.

Expected behaviour:
- I can type any tags I choose, separating them with commas or similar.
- A drop-down list appears whilst typing, but that is to help with autocompletion, rather than to force use of pre-existing tags.
- Any tags (any pre-populated tags, at least) should be in the users' language.

**Comment by mjlescano** [comment]
Hi @lee-b, thanks for reporting this :D
We're planning to fix this in the next 3 weeks.

Right now `tags` are global, can only be created by `STAFF` members and can only be one per `topic`. And that sucks 😛 .

First, what now we call `tags` are more like categories. So, first, we should rename `tags` to `category`, and be able to define categories per-democracy, only by the democracy owner/administrators.

Then, create `tags` that work more like twitter's hashtags. Which are global, and can be created by anyone.

Any thoughts?

**Comment by franciclo** [comment]
I like the idea of using tags freely, with autocompletion, so that you can join a trend, and later query by tags, i also believe that this feature can cover the need for categories (#enviromental #greenspaces)
Also topics could have different formats like templates, to help dividing sections and styling them, like law project, ideas to discuss, polls, support for a campaign or movilisation, etc..

**Comment by franciclo** [comment]
tags are being implemented in current version and being improved in next versions.
