### ISSUE TITLE
Build fails when running latest pull.

### ISSUE THREAD

**Issue by steowens** [DemocracyOS/democracyos#1286]
While executing make I get several warnings and eventually the build fails.  From the looks of things it would seem that the package.json is either out of date or not compatible with the version of NPM I am running:  3.5.2

Is this application designed to run with legacy node?

Here is the list of warnings:
```
root@ubuntu-512mb-sfo1-01:~/democracyos# make
Installing dependencies...
loadDep:yargs → resolveWi ▌ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine locale@0.0.20: wanted: {"node":">0.8.x <=1.0.0"} (current: {"node":"npm WARN deprecated gulp-minify-css@1.1.0: Please use gulp-clean-css
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated lodash@2.4.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated native-or-bluebird@1.1.2: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated tough-cookie@1.2.0: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
^CMakefile:24: recipe for target 'packages' failed░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
make: *** [packages] Interrupt
```

**Comment by gvilarino** [comment]
Yeah, this probably has to do with some environment condition; such as `node` or `npm` versions. `docker-compose up` should do the trick; we must investigate your particular issue

**Comment by oxitech239** [comment]
Docker does no work either, complains about most any configuration line set in docker-compose.yml

**Comment by oxitech239** [comment]
I've had to manually do 'npm install commander' to have some things working

It also appears many npm in packages.json are throwing a warning. Manually adjusting package.json to reduce warnings had partial success.

**Comment by oxitech239** [comment]
---- notable is it always reports Killed at various stages, sometimes it seems to finalise then 'killed'

# npm install
loadDep:yargs → get       ▀ ╢███████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated lodash@2.4.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
npm WARN deprecated native-or-bluebird@1.1.2: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated tough-cookie@1.2.0: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
loadDep:stylus → request  ▌ ╢█████████████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
Killed

**Comment by oxitech239** [comment]
i have NODE_PATH=. and NODE_PATH=development set
i also have GITHUB_USERNAME=mytokenstring and GITHUB_PASSWORD=x-oauth-basic set

I've tried 'make' and 'npm install' for tag 1.4.0 1.3.0 1.1.0 and all fail in the same way as per below
Makefile:24: recipe for target 'packages' failed

all this is on Ubuntu 16.04 LTS

**Comment by oxitech239** [comment]
maybe nice to know, i have to 'npm install commander' for each branch/tag 
before i run 'NODE_ENV=development . node bin/dos-install --config' 
as to create the config/development.json file

**Comment by mjlescano** [comment]
@oxitech239 looks like you where following the instructions of the wiki that is deprecated (I'm going to add another clarification). With the docs on http://docs.democracyos.org/install.html should work :)
