### ISSUE TITLE
Add Moderator role

### ISSUE THREAD

**Issue by franciclo** [DemocracyOS/democracyos#1362]
## Context
Right now the only moderation tool is that any user can flag a comment. And when a comment gets a configurable ammount of flags, it gets faded.

## Moderator Role

The moderator should be able of:
- Delete Comments
  * This option shouldn't be available by default. As is required by special use cases like goverments.
- Tag comments (not implemented yet)
- Search comments by replies, votes, author, tag

## Tools for the Moderator

* **Comments Admin:** This actions will require a special admin section that provide query and action capabilities.
* **Comment Create Notification:** Tell all the moderators when anyone comments a Topic.

**Comment by franciclo** [comment]
@inti suggested that a deletedAt property could be used for moderator's deletions so someone could check what comments have been deleted by moderators.

**Comment by franciclo** [comment]
Moderators could also be able to add and edit user badges. This would give recognition to experts or relevant users.

**Comment by gvilarino** [comment]
I generally agree that a moderation role would be useful in some cases/scenarios. Some thoughts:

A moderator should (must?) include a reason for deletion, which should be publicly visible to other members of the forum/topic.

Any deleted comment/reply should be immediately notified to the author, with the reason.

Deleted comments/replies should be visible under a different view/filter, and should be disclosable: i.e.: instead of not showing them, show a "This comment/reply was deleted by <moderator name> because <reason>" and a "Reveal" button that would show the original comment (this makes the user acknowledge they're viewing a deleted comment/reply and still maintain the principle of not censoring free speech).

Now some comments on the OP:

> Search comments by replies, votes, author, tag
This should be available to all users, not just moderators. Also, I think it's beyond the scope of this issue.

> *Comment Create Notification:* Tell all the moderators when anyone comments a Topic.
Be careful with swamping moderators with notifications; this is very likely to reduce mailer reputation and flag the app email sender as spam. Emails should be sent once every X hours with a digest instead. A web view of this should look like Github's notification center, each balloon for a forum in the deployment.

> Moderators could also be able to add and edit user badges. This would give recognition to experts or relevant users.
I would not push gamification/reputation aspects on this issue; entirely out of scope.

**Comment by mjlescano** [comment]
> Search comments by replies, votes, author, tag
> This should be available to all users, not just moderators. Also, I think it's beyond the scope of this issue.
Yup, 👉 https://github.com/DemocracyOS/democracyos/issues/1365

> Comment Create Notification: Tell all the moderators when anyone comments a Topic.
> Be careful with swamping moderators with notifications; this is very likely to reduce mailer reputation and flag the app email sender as spam. Emails should be sent once every X hours with a digest instead. A web view of this should look like Github's notification center, each balloon for a forum in the deployment.
I agree everything, but we opted for this solution for simplicity, any decent email client has filtering options. Follow up here: https://github.com/DemocracyOS/democracyos/issues/1366

**Comment by franciclo** [comment]
> Moderators could also be able to add and edit user badges. This would give recognition to experts or relevant users.
> I would not push gamification/reputation aspects on this issue; entirely out of scope.

I think the role of the moderator is to remove the bad comments and to improve the good comments as well.
For example in a public auditory moderators would like to validate the expertise of some commenter.

**Comment by mjlescano** [comment]
I'm closing this issue because the Moderator role is already implemented.
