### ISSUE TITLE
Add Auth0 as authentication method alternative

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/democracyos#1412]
A service like Auth0 will give us complete flexibility for new authentication methods. And it will be a solution to implement not-so-mainstream auth methods like on #1209

* The default auth method should be email, as always.
* An option to disable email auth should be added, for the case that someone want's to use only facebook or auth0.
* Facebook auth should be leaved as-is, beign the more mainstream auth and to not force the usage of Auth0.

**Comment by leog** [comment]
Hey @mjlescano. I think it could be pretty straightforward to implement if you consider using https://github.com/auth0/passport-auth0. Seems like DOS is already using passport so integrating a passport integration with auth0 could be the solution for this enhancement.

**Comment by gvilarino** [comment]
@leog while your assessment is correct, we will not implement auth0 as part of DOS since it's a paid, closed source, 3rd party tool. While I love them and use the service for my for-profit endeavors, DemocracyOS has a commitment with the Free Software movement and thus we only make mandatory stuff that can be either solved with FLOSS or easy to circumvent by hacking it yourself.

What would be acceptable, in any case, would be that we support 3rd party identity provider services (of which Auth0 would be a possible solution) but just indicating where to integrate; we must always support open alternatives like username/password, LDAP or SAML, the latter being super specific to big SSO-enabled organisations.

**Comment by leog** [comment]
@gvilarino I completely understand. 

If that's the case, could you please provide guidance on where to integrate such a passport identity provider to support auth0 on our fork?

Thanks.

**Comment by gvilarino** [comment]
@leog I'd go with the official passport strategy for auth0 https://github.com/auth0/passport-auth0

**Comment by mjlescano** [comment]
@leog if you do it in a way that is not mandatory to use auth0, we would love to merge it :)

Its the same logic we use with facebook login, open stuff by default, and optional-not-mandatory services for specific cases.

**Comment by leog** [comment]
@mjlescano @gvilarino gotcha.

Just to be sure, we would need to create a new `auth-auth0` like the àuth-facebook` one here: https://github.com/DemocracyOS/democracyos/tree/master/lib/site/auth-facebook. Is that correct?

Thanks for the support!

**Comment by mjlescano** [comment]
Yup, for a starting point is a really good idea to mimic FB auth. The only difference is that auth0 allows multiple auth strategies ([se the usage section on the README](https://github.com/auth0/passport-auth0#usage)), but I wouldn't mind about that and let auth0 to handle it, because it would be really hard to make a configuration flexible and easy to understand.

**Comment by franciclo** [comment]
Closing since we don't plan to add auth0 support
