### ISSUE TITLE
No mails / notifications for a new installation

### ISSUE THREAD

**Issue by AlexLyko** [DemocracyOS/democracyos#1471]
Hello, I work for the French Biodiversity Agency. We'd like to use DemocracyOs to let a wilder audience helps public decision in ecology, and manage to deploy it... 

But we face a notification issue : no mail is sent by the application 
- when service is set to 'mailer', we get a ERRCONN 587 error, 
- when we set it to gmail the entry is added to mongo but it never seems to be processed - the mail is never received). 

It is not clear in the documentation if a Notifier instance need to be set up separately (isn't it 'embedded' ?).
Can we get some help ? Thanks in advance !

**Comment by AlexLyko** [comment]
Solved using an external SMTP service, putting mailer to {} and adding properties into nodemailer only. Not specified into documentation. By the way, I had to set up numerous MongoDb versions and the last one working was 3.4. Have a nice day.

**Comment by ZerooCool** [comment]
Hello,
Can you give more info ?
I have Debian Stretch 9
Docker, image DemocracyOS, image MongoDB ( only )

How to configure for the mails to be sent?
For the moment, I do not receive anything in my box.

**Comment by franciclo** [comment]
take a look at #1478 for details with mailing configuration

**Comment by ZerooCool** [comment]
I realize that I did not have **NodeJS**.
I'm using this command in my DemocracyOS Docker container.
Finally, **the mails arrive**, it was long to come.

curl -sL https://deb.nodesource.com/setup_6.x | bash -
apt-get install -y nodejs

Now my **account is validated**, but other difficulties are coming up.
The **email I receive has the following form**:
http://**mongo:3000**/signup/validate/5bb6a42326c9
**I can not click to validate it**.
I get around this problem by sending back the message, and, changing mongo:3000 by my domain.ext
**Do you know how to do it from the configuration, to fix that?**

I still can not login, probably because I did not add the name of the administrator in the configuration.
