### ISSUE TITLE
Delete user script

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/democracyos#464]
We need a script for deleting a user from the database. This is required by some implementations.

When deleting a user, we should consider deleting:
- [ ] All user's comments, as well as any replies to them, upvotes and downvotes.
- [ ] All user's votes
- [ ] All user's upvotes/downvotes
- [ ] All user's preferences.
- [ ] The `user` itself.

Check all models under `lib/models` to understand relationships between different schemas.

**Comment by NazarenoL** [comment]
@gvilarino 
I can think of many ways to do this, and a few things to discuss:
1. Do what @slifszyc suggested of explaining that user contributions won't be hard-deleted, but, for example, if you want to delete an user that has been spamming through all the site, it would be ideal to delete everything at once.
2. Develop a function that executes all the queries required to delete the user related contents. 
3. The most KISS way would be to define in the database triggers for the foreign keys/relationships (ON DELETE CASCADE...`), and it would ensure consistent data, even if the admin chooses to delete someone directly from the database. 

I would also recommend a few things (That could be implemented both on B or C options):
* I think that a good idea, currently used in plenty of sites, is to instead of deleting the user  all the replies, replace the comment text for an alert/notice that says that it was deleted, while you can still see all the replies.

**Comment by NazarenoL** [comment]
@gvilarino 
I can think of many ways to do this, and a few things to discuss:
1. Do what @slifszyc suggested of explaining that user contributions won't be hard-deleted, but, for example, if you want to delete an user that has been spamming through all the site, it would be ideal to delete everything at once.
2. Develop a function that executes all the queries required to delete the user related contents. 
3. The most KISS way would be to define in the database triggers for the foreign keys/relationships (`ON DELETE CASCADE...`), and it would ensure consistent data, even if the admin chooses to delete someone directly from the database. 

**I also have some recommendations: ** (That could be implemented on the last 2 options):
* I think that a good idea, currently used in plenty of sites, is to instead of deleting the user comments with all its replies (As some of them could have interesting replies), replace the comment text for an alert/notice that says that it was deleted, but leaving all the replies available.
* **Allow 2 different functions:** *Delete an user*, or *ban him*. Banning the user won't delete any content, but would log out him and won't let him login again (It would show him a message telling this). We could even implement temporary bans.

**Comment by NazarenoL** [comment]
Oh. I just noticed that all the db is using MongoDB (What I, personally, think was a bad decision for this data schema/structure). There aren't relationships or cascade effects, so there is no *clean* way to do this. This wont allow option **2.** to be implemented.

**Comment by palmerabollo** [comment]
I agree that removing a user would be useful in many scenarios (i.e. delete a spammer). Regarding **option 3**, with mongoose you can kind of achieve cascade effects:

```javascript
UserSchema.pre('remove', function(next) {
    Vote.remove({author: this._id}).exec();
    Flag.remove({author: this._id}).exec();
    // ... other relationships
    next();
});
```
It should also recalculate some "denormalized fields" such as comment scores, etc. (BTW I can't see how the score is updated [when a user unvotes](https://github.com/DemocracyOS/app/blob/development/lib/models/comment.js#L183))

I like @NazarenoL's recommendations: The idea of banning vs deleting (this could be addressed in a different issue) and keeping a notice that says a comment was deleted. Regarding this, do you think removing a comment's author (i.e. Comment.author=undefined) but keeping the text of the comment itself would be a good idea? This way you anonymize the comment but we keep its text to avoid losing context in discussions.

**Comment by gvilarino** [comment]
@NazarenoL I agree `mongodb` may not be great for these kind of operations out-of-the-box, but a simple indexing policy and what @palmerabollo suggested do the trick. Still, this is just a script that won't be run a lot (ideally never) and is only intended for providing a solution to a very specific implementor's need (moreso, for developers trying to delete test users)
